
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb8\xe9h=\x80\xd7bJ\x05So\xdc\xec\x01%\xa5'
    
_lr_action_items = {'RPAREN':([2,6,7,8,9,10,11,12,13,14,],[-1,-5,11,-7,-6,-6,-2,-4,14,-3,]),'NUMBER':([0,3,4,9,10,],[2,2,2,2,2,]),'LBRACKET':([0,3,4,9,10,],[3,3,3,3,3,]),'COMMA':([2,6,7,8,11,14,],[-1,9,10,-7,-2,-3,]),'LPAREN':([0,3,4,9,10,],[4,4,4,4,4,]),'RBRACKET':([2,3,5,6,8,9,11,12,14,],[-1,-6,8,-5,-7,-6,-2,-4,-3,]),'$end':([1,2,8,11,14,],[0,-1,-7,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'items':([3,9,10,],[5,12,13,]),'exp':([0,3,4,9,10,],[1,6,7,6,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> NUMBER','exp',1,'p_exp_number','C:/Users/daybreaklee/Udacity/Building_Web_browser/ProgrammingLanguages_Udacity/TerribleTuple_7_2.py',48),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_number_encolsed','C:/Users/daybreaklee/Udacity/Building_Web_browser/ProgrammingLanguages_Udacity/TerribleTuple_7_2.py',52),
  ('exp -> LPAREN exp COMMA items RPAREN','exp',5,'p_exp_tuple','C:/Users/daybreaklee/Udacity/Building_Web_browser/ProgrammingLanguages_Udacity/TerribleTuple_7_2.py',56),
  ('items -> exp COMMA items','items',3,'p_items','C:/Users/daybreaklee/Udacity/Building_Web_browser/ProgrammingLanguages_Udacity/TerribleTuple_7_2.py',60),
  ('items -> exp','items',1,'p_items_last','C:/Users/daybreaklee/Udacity/Building_Web_browser/ProgrammingLanguages_Udacity/TerribleTuple_7_2.py',64),
  ('items -> <empty>','items',0,'p_items_empty','C:/Users/daybreaklee/Udacity/Building_Web_browser/ProgrammingLanguages_Udacity/TerribleTuple_7_2.py',68),
  ('exp -> LBRACKET items RBRACKET','exp',3,'p_exp_liste','C:/Users/daybreaklee/Udacity/Building_Web_browser/ProgrammingLanguages_Udacity/TerribleTuple_7_2.py',72),
]
